### ISSUE TITLE
CancellationToken 

### ISSUE THREAD

**Issue by ghyujkilop** [EzioTheDeadPoet/Weightless-Misc-Items#2]
No extra data to consider
```
Compiling
("C:\Users\username\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\152bd150.ycc\Runner\Weightless-Misc-Items"): "dotnet" "build \"Weightless-Misc-Items.csproj\" --runtime win-x64 -c Release"
Compiled
Sha "aa040d654c3ecfeb8ddb7ffdb31e7cb09d3831c7"
(""): "dotnet" "run --project \"C:\Users\username\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\152bd150.ycc\Runner\Weightless-Misc-Items\Weightless-Misc-Items.csproj\" --runtime win-x64 -c Release --no-build check-runnability --DataFolderPath D:\Mods\SE\Data --GameRelease SkyrimSE --LoadOrderFilePath \"C:\Users\username\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Plugins.txt\""
Running
(""): "dotnet" "run --project \"C:\Users\username\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\152bd150.ycc\Runner\Weightless-Misc-Items\Weightless-Misc-Items.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath D:\Mods\SE\Data --ExtraDataFolder \"D:\Mods\MO\Utilities\Synthesis\Data\Skyrim Special Edition\Weightless-Misc-Items\" --GameRelease SkyrimSE --LoadOrderFilePath \"C:\Users\username\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Plugins.txt\" --OutputPath \"C:\Users\username\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\1 - Weightless-Misc-Items\" --PatcherName Weightless-Misc-Items --SourcePath \"C:\Users\username\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\1 - ExperienceMutagenPatcher\""
Mutagen version: 0.33.2
Mutagen sha: f14bb1e2d9591e1f23e4785686fb22db7c22365a
Synthesis version: 0.20.4
Synthesis sha: c2f7d7adcde3c39ad375b6ef1053e3b6836609fb
run-patcher --DataFolderPath D:\Mods\SE\Data --ExtraDataFolder "D:\Mods\MO\Utilities\Synthesis\Data\Skyrim Special Edition\Weightless-Misc-Items" --GameRelease SkyrimSE --LoadOrderFilePath "C:\Users\username\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Plugins.txt" --OutputPath "C:\Users\username\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\1 - Weightless-Misc-Items" --PatcherName Weightless-Misc-Items --SourcePath "C:\Users\username\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\1 - ExperienceMutagenPatcher"
Prepping state.
Reading settings: D:\Mods\MO\Utilities\Synthesis\Data\Skyrim Special Edition\Weightless-Misc-Items\settings.json
System.NullReferenceException: Object reference not set to an instance of an object.
   at SlotsSlotsSlots.Program.MagicEffects(IPatcherState`2 state) in C:\Users\username\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\152bd150.ycc\Runner\Weightless-Misc-Items\Program.cs:line 151
   at SlotsSlotsSlots.Program.RunPatch(IPatcherState`2 state) in C:\Users\username\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\152bd150.ycc\Runner\Weightless-Misc-Items\Program.cs:line 44
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 101
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 507
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 428
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 400
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(ModKey outputKey, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, String persistencePath)
```

**Comment by EzioTheDeadPoet** [comment]
Use xEdit and use the check for errors script and fix any errors you find.

This issue is likely caused by a bad setup.
