### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by selsie** [EzioTheDeadPoet/Weightless-Misc-Items#3]
The patcher won't work on my loadlist, I'm ALWAYS getting
```
Reading settings: D:\Games\steamapps\common\Tools\Synthesis\Data\Skyrim Special Edition\Weightless-Misc-Items\settings.json
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Mutagen.Bethesda.Plugins.Binary.Translations.BinaryStringUtility.ProcessNullTermination(ReadOnlySpan`1 bytes)
   at Mutagen.Bethesda.Plugins.Binary.Translations.BinaryStringUtility.ProcessWholeToZString(ReadOnlySpan`1 bytes)
   at Mutagen.Bethesda.Plugins.Binary.Translations.BinaryStringUtility.ParsePrependedString(ReadOnlyMemorySlice`1 span, Byte lengthLength)
   at Mutagen.Bethesda.Skyrim.Internals.AlternateTextureBinaryOverlay.get_Name()
   at Mutagen.Bethesda.Skyrim.Internals.AlternateTextureSetterTranslationCommon.DeepCopyIn(IAlternateTexture item, IAlternateTextureGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.AlternateTextureSetterTranslationCommon.DeepCopy(IAlternateTextureGetter item, ErrorMaskBuilder errorMask, TranslationCrystal copyMask)
   at Mutagen.Bethesda.Skyrim.AlternateTextureMixIn.DeepCopy(IAlternateTextureGetter item, ErrorMaskBuilder errorMask, TranslationCrystal copyMask)
   at Mutagen.Bethesda.Skyrim.Internals.ModelSetterTranslationCommon.<>c__DisplayClass1_0.<DeepCopyIn>b__0(IAlternateTextureGetter r)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Noggog.ExtendedList`1..ctor(IEnumerable`1 collection) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Containers\ExtendedList.cs:line 16
   at Noggog.EnumerableExt.ToExtendedList[T](IEnumerable`1 e) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\EnumerableExt.cs:line 277
   at Mutagen.Bethesda.Skyrim.Internals.ModelSetterTranslationCommon.DeepCopyIn(IModel item, IModelGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.ModelSetterTranslationCommon.DeepCopy(IModelGetter item, ErrorMaskBuilder errorMask, TranslationCrystal copyMask)
   at Mutagen.Bethesda.Skyrim.ModelMixIn.DeepCopy(IModelGetter item, ErrorMaskBuilder errorMask, TranslationCrystal copyMask)
   at Mutagen.Bethesda.Skyrim.Internals.MiscItemSetterTranslationCommon.DeepCopyIn(IMiscItem item, IMiscItemGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.MiscItemSetterTranslationCommon.DeepCopyIn(IMajorRecord item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Plugins.Records.Internals.MajorRecordSetterTranslationCommon.DeepCopyIn(IMajorRecordInternal item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.SkyrimMajorRecordSetterTranslationCommon.DeepCopyIn(ISkyrimMajorRecordInternal item, ISkyrimMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.MiscItemSetterTranslationCommon.DeepCopyIn(IMiscItemInternal item, IMiscItemGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.MiscItemSetterTranslationCommon.DeepCopy(IMiscItemGetter item, TranslationMask copyMask)
   at Mutagen.Bethesda.Skyrim.MiscItemMixIn.DeepCopy(IMiscItemGetter item, TranslationMask copyMask)
   at SlotsSlotsSlots.Program.RunPatch(IPatcherState`2 state) in C:\Users\Ranbi\AppData\Local\Temp\Synthesis\2bb878d8-510a-4adb-bb95-00e8a35c3d60\Git\dcti45ch.ndb\Runner\Weightless-Misc-Items\Program.cs:line 44
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 94
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 456
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 404
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 378
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(ModKey outputKey, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, String persistencePath)
```

**Comment by EzioTheDeadPoet** [comment]
Can't reproduce.
