### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ghyujkilop** [EzioTheDeadPoet/Weightless-Misc-Items#4]
Everytime I try run this I get:
```exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at SlotsSlotsSlots.Program.MagicEffects(IPatcherState`2 state) in C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\152bd150.ycc\Runner\Weightless-Misc-Items\Program.cs:line 151
   at SlotsSlotsSlots.Program.RunPatch(IPatcherState`2 state) in C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\152bd150.ycc\Runner\Weightless-Misc-Items\Program.cs:line 44
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 99
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 552
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 449
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 412
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRunner.cs:line 52
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRun.cs:line 52
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(IGroupRun groupRun, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAPatcher.cs:line 65
   at Synthesis.Bethesda.Execution.Running.Runner.RunSomePatchers.Run(IGroupRun groupRun, PatcherPrepBundle[] patchers, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunSomePatchers.cs:line 36
   at Synthesis.Bethesda.Execution.Running.Runner.RunAGroup.Run(IGroupRun groupRun, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAGroup.cs:line 59
   at Synthesis.Bethesda.Execution.Running.Runner.RunAllGroups.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAllGroups.cs:line 36
   at Synthesis.Bethesda.Execution.Running.Runner.ExecuteRun.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\ExecuteRun.cs:line 54
   at Synthesis.Bethesda.GUI.Services.Profile.Running.ExecuteGuiRun.Run(IEnumerable`1 groupRuns, PersistenceMode persistenceMode, Boolean localize, Boolean utf8InEmbeddedStrings, Language targetLanguage, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\Services\Profile\Running\ExecuteGuiRun.cs:line 47
   at Synthesis.Bethesda.GUI.ViewModels.Profiles.Running.RunVm.<Run>b__39_1(Unit _) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\ViewModels\Profiles\Running\RunVm.cs:line 200
```

**Comment by EzioTheDeadPoet** [comment]
Looks like you are running an outdated version of the patcher because the latest version has no thing related to the log at the inidicated line 151.

**Comment by ghyujkilop** [comment]
> Looks like you are running an outdated version of the patcher because the latest version has no thing related to the log at the inidicated line 151.

Here's a picture showing the correct version I'm using: https://i.imgur.com/8nHjmZV.png it doesn't have an option to update it. How would I get the latest? Unless I am already on the latest.

**Comment by EzioTheDeadPoet** [comment]
Set mutagen and synthesis to match then. If that doesn't work, then something is fishy with your load order.--Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 7/8/22, 23:19 ghyujkilop ***@***.***> wrote:

   
   
   Looks like you are running an outdated version of the patcher because the latest version has no thing related to the log at the inidicated line 151. 
   
  Here's a picture showing the correct version I'm using: https://i.imgur.com/8nHjmZV.png it doesn't have an option to update it. How would I get the latest? Unless I am already on the latest.

**Comment by ghyujkilop** [comment]
Heyo, just reset this again, using 23.3, match & auto, And received this one: `Compiling
No extra data to consider
("C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\152bd150.ycc\Runner\Weightless-Misc-Items"): "dotnet" "build \"Weightless-Misc-Items.csproj\" --runtime win-x64 -c Release"
Compiled
Sha "aa040d654c3ecfeb8ddb7ffdb31e7cb09d3831c7"
Running
(""): "dotnet" "run --project \"C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\152bd150.ycc\Runner\Weightless-Misc-Items\Weightless-Misc-Items.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath D:\Mods\SE\Data --ExtraDataFolder \"D:\Mods\MO\Utilities\Synthesis\Data\Skyrim Special Edition\Weightless-Misc-Items\" --GameRelease SkyrimSE --ModKey Synthesis.esp --LoadOrderFilePath \"C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Synthesis\Plugins.txt\" --LoadOrderIncludesCreationClub --OutputPath \"C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Synthesis\1 - Weightless-Misc-Items\Synthesis.esp\" --PatcherName Weightless-Misc-Items"
Mutagen version: 0.31
Mutagen sha: cf708daf0b89c643b94bf08c28e7ab2a719d9451
Synthesis version: 0.19.3
Synthesis sha: e765ef1333b34f3ded15de6ed5ec18983ee48c36
run-patcher --DataFolderPath D:\Mods\SE\Data --ExtraDataFolder "D:\Mods\MO\Utilities\Synthesis\Data\Skyrim Special Edition\Weightless-Misc-Items" --GameRelease SkyrimSE --LoadOrderFilePath "C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Synthesis\Plugins.txt" --OutputPath "C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Workspace\Synthesis\1 - Weightless-Misc-Items\Synthesis.esp" --PatcherName Weightless-Misc-Items
Prepping state.
Reading settings: D:\Mods\MO\Utilities\Synthesis\Data\Skyrim Special Edition\Weightless-Misc-Items\settings.json
System.NullReferenceException: Object reference not set to an instance of an object.
   at SlotsSlotsSlots.Program.MagicEffects(IPatcherState`2 state) in C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\152bd150.ycc\Runner\Weightless-Misc-Items\Program.cs:line 142
   at SlotsSlotsSlots.Program.RunPatch(IPatcherState`2 state) in C:\Users\Dat Boi\AppData\Local\Temp\Synthesis\p1tqdjmr.ijc\Git\152bd150.ycc\Runner\Weightless-Misc-Items\Program.cs:line 35
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 94
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 456
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 404
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 378
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRunner.cs:line 52
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRun.cs:line 52
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(IGroupRun groupRun, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAPatcher.cs:line 65
   at Synthesis.Bethesda.Execution.Running.Runner.RunSomePatchers.Run(IGroupRun groupRun, PatcherPrepBundle[] patchers, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunSomePatchers.cs:line 36
   at Synthesis.Bethesda.Execution.Running.Runner.RunAGroup.Run(IGroupRun groupRun, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAGroup.cs:line 59
   at Synthesis.Bethesda.Execution.Running.Runner.RunAllGroups.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAllGroups.cs:line 36
   at Synthesis.Bethesda.Execution.Running.Runner.ExecuteRun.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\ExecuteRun.cs:line 54
   at Synthesis.Bethesda.GUI.Services.Profile.Running.ExecuteGuiRun.Run(IEnumerable`1 groupRuns, PersistenceMode persistenceMode, Boolean localize, Boolean utf8InEmbeddedStrings, Language targetLanguage, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\Services\Profile\Running\ExecuteGuiRun.cs:line 47
   at Synthesis.Bethesda.GUI.ViewModels.Profiles.Running.RunVm.<Run>b__39_1(Unit _) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\ViewModels\Profiles\Running\RunVm.cs:line 200`

Along with le ol': Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRunner.cs:line 52
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRun.cs:line 52
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(IGroupRun groupRun, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAPatcher.cs:line 65
   at Synthesis.Bethesda.Execution.Running.Runner.RunSomePatchers.Run(IGroupRun groupRun, PatcherPrepBundle[] patchers, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunSomePatchers.cs:line 36
   at Synthesis.Bethesda.Execution.Running.Runner.RunAGroup.Run(IGroupRun groupRun, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAGroup.cs:line 59
   at Synthesis.Bethesda.Execution.Running.Runner.RunAllGroups.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAllGroups.cs:line 36
   at Synthesis.Bethesda.Execution.Running.Runner.ExecuteRun.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\ExecuteRun.cs:line 54
   at Synthesis.Bethesda.GUI.Services.Profile.Running.ExecuteGuiRun.Run(IEnumerable`1 groupRuns, PersistenceMode persistenceMode, Boolean localize, Boolean utf8InEmbeddedStrings, Language targetLanguage, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\Services\Profile\Running\ExecuteGuiRun.cs:line 47
   at Synthesis.Bethesda.GUI.ViewModels.Profiles.Running.RunVm.<Run>b__39_1(Unit _) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\ViewModels\Profiles\Running\RunVm.cs:line 200

**Comment by EzioTheDeadPoet** [comment]
Did you maybe change a setting ?

I might update the dependencies tomorrow and if my IDE screams at me with warnings then I will fix them. But I am not interested in this Patcher anymore sine it isn't one of my passion projects and was a "people pleaser" instead.

**Comment by EzioTheDeadPoet** [comment]
@ghyujkilop should be fixed now.
